"""empty message

Revision ID: 55e802261117
Revises:
Create Date: 2025-04-22 14:58:29.066178

"""

import sqlalchemy as sa
from alembic import op

import app.core.types

revision = "55e802261117"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("avatar", app.core.types.FSSpecField(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_model")
    # ### end Alembic commands ###
